---
stages:
- name: Load Chatbot Assets
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |
      #!/bin/bash
      export CHATBOT_JSON_URL=${CHATBOT_JSON_URL}
      env
