---
stages:
- name: Deploy Chatbot
  properties:
  - name: CHATBOT_JSON_URL
    value: '${CHATBOT_JSON_URL}'
    type: text
  - name: CHATBOT_NAME
    value: '${CHATBOT_NAME}'
    type: text
  jobs:
  - name: Deploy Chatbot Assets
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: Load Chatbot Assets
    script: |
      #!/bin/bash -ex
      # Fetch the workspace json from the marketplace
      # This is largely lifted from:
      #  https://github.com/open-toolchain/watson-training-toolchain/blob/master/.bluemix/pipeline.yml

      if ! curl -L -o workspace.json "$CHATBOT_JSON_URL"; then
        echo "Failed to fetch workspace for chatbot $CHATBOT_NAME from $CHATBOT_JSON_URL."
        exit 1
      fi

      # List the conversation services, for example:
      # $ cf services | grep conversation
      # Chatbot-20170822164726835   conversation          free                create succeeded
      # Conversation-hf             conversation          free                create succeeded
      # NOTE: the -c option for grep counts number of rows
      result=$(cf services | grep -c conversation)

      # if no consersation exists, create service and service key, name after the chatbot
      if [ "$result" -eq 0 ]; then
        cf create-service conversation free "$CHATBOT_NAME"
        cf create-service-key "$CHATBOT_NAME" "$CHATBOT_NAME"
      # if more than one exists, issue a warning
      elif [ "$result" -gt 1 ]; then
        echo "found more than one conversation service, using the first found"
        # TODO: Use the paid service over the free?
      fi
      # Finally, we get the service name, either newly created or first result
      service_name=$(cf services | grep conversation | cut -d " " -f1)

      # Fetch service key name for the service, for example:
      # $ cf service-keys Conversation-hf
      # Getting keys for service instance Conversation-hf
      #
      # name
      # Credentials-1
      # NOTE: Use tail -1 to get the last line in the output
      # TODO: What if there are multiple service keys?
      credentials=$(cf service-keys "$service_name" | tail -1)

      # Fetch the service key credentials, parse it with json, for example:
      # $ cf service-key Conversation-hf Credentials-1
      # Getting key Credentials-1 for service instance Conversation-hf
      #
      # {
      # "password": "superSecretFakePassword",
      # "url": "https://gateway.watsonplatform.net/conversation/api",
      # "username": "fe874f2f-73bb-4698-8b09-e43ffe89629a"
      # }
      npm install -g json
      jsonkey=$( cf service-key "$service_name" "$credentials" | tail -n +3 )
      wcuser=$( echo $jsonkey | json username )
      wcpass=$( echo $jsonkey | json password )
      wcurl=$( echo $jsonkey | json url )

      # Create workspace and train it
      resp=$( curl --user $wcuser:$wcpass \
                 -H "Content-Type: application/json" \
                 -X POST -d @workspace.json \
                 $wcurl/v1/workspaces?version=2017-04-21 )
      echo $resp| json
      export WORKSPACE_ID=$( echo $resp | json workspace_id )
      if [ -z "${WORKSPACE_ID}" ]; then
        echo "Failed creating new workspace..."
        echo "If too many workspaces already, discard obsolete workspaces using: "
        echo "https://www.ibmwatsonconversation.com"
        echo "Select service instance:$CHATBOT_NAME in current org&space"
        exit 1
      fi
      echo "##############################################################"
      echo "Created and trained new workspace: WORKSPACE_ID: ${WORKSPACE_ID}"
      echo "##############################################################"

      resp=$( curl --user $wcuser:$wcpass -X GET \
              $wcurl/v1/workspaces/$WORKSPACE_ID?version=2017-04-21 )
      status=$?
      echo $resp| json
      resp_wsid=$( echo $resp | json workspace_id )
      if [ $status -ne 0 ] || [ "$resp_wsid" != "$WORKSPACE_ID" ]; then
        echo "Invalid workspace: $WORKSPACE_ID"
        echo "Administer your workspaces at: https://www.ibmwatsonconversation.com"
        exit 1
      fi
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish
