---
stages:
- name: Deploy Chatbot
  properties:
  - name: CHATBOT_JSON_URL
    value: '${CHATBOT_JSON_URL}'
    type: text
  - name: CHATBOT_NAME
    value: '${CHATBOT_NAME}'
    type: text
  jobs:
  - name: Deploy Chatbot Assets
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: Load Chatbot Assets
    script: |-
      #!/bin/bash
      # XXX: Update this URL when the repo finds a home
      git clone https://git.ng.bluemix.net/adam.gandelman/chatbot-deploy/
      cd chatbot-deploy
      pip install -r requirements.txt
      python ./scripts/deploy.py
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish
